version: '2'
services:
  firefox:
    image: selenium/standalone-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"